[profile.default]
src = 'src'
test = 'test'
script = 'script'
libs = ['lib']
solc_version = '0.8.24'
optimizer = true
optimizer_runs = 200
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

[fuzz]
max_test_rejects = 1024
runs = 256

[invariant]
fail_on_revert = true

[fmt]
line_length = 100
