name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  solidity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge build && forge test --gas-report

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
        working-directory: sdk
      - run: npm install -g solhint
      - run: solhint 'contracts/**/*.sol'
      - run: pnpm lint
        working-directory: sdk

  sdk-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
      - run: pnpm install --frozen-lockfile
        working-directory: sdk
      - run: pnpm test
        working-directory: sdk
